### ISSUE TITLE
[汉明]关于组管理列表批量更新的接口需求修改

### ISSUE THREAD

**Issue by scosun** [TimYi/FengHuang#19]
@天明 在组管理中，我需要能一次性保存多条数据 ，格式如下：[{"id":"404040e64dd6fa3b014dd6fbeed00000","name":"测试组","minExp":0,"maxExp":10000,"stars":5,"color":null,"selected":false}]

因为在组管理中有这么个功能
![1 xh35igxbat 9 nt 0](https://cloud.githubusercontent.com/assets/6879873/8072950/d3f8f06a-0f50-11e5-98ca-0685655ef43a.png)

**Comment by TimYi** [comment]
需要按照json list格式保存。
