### ISSUE TITLE
排序、过滤功能异常

### ISSUE THREAD

**Issue by feegle** [TimYi/FengHuang#25]
约定：
排序、过滤格式
{
	filter_operation1_param1:value,
	filter_operation2_param2:value,
	sort_param1:desc,
	sort_param2:desc
}
但按此格式进行查询时异常，如：
get : http://101.200.229.135:8080/api/admin/message?sort_create_user=desc
return :org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.data.mapping.PropertyReferenceException: No property create found for type Message!
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)....

**Comment by TimYi** [comment]
sort语句写错了
